version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir -r backend/requirements.txt && python scripts/generate_sample_data.py && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  web:
    image: node:20-alpine
    working_dir: /app/frontend
    command: sh -lc "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    depends_on:
      - api 